---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sources/
- kustomizations/
- cluster/

patches:
# yamllint disable-line rule:indentation
- patch: |-
    kind: irrelevant
    metadata:
      name: irrelevant
      annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
  target:
    kind: "(GitRepository|Kustomization)"
# yamllint disable-line rule:indentation
- patch: |-
    - op: replace
      path: /spec/prune
      value: false
  target:
    kind: Kustomization

sortOptions:
  order: fifo
