---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-migration-import-credentials
  namespace: garage
spec:
  data:
  - secretKey: access-key-id
    remoteRef:
      key: cluster_homelab_garage_migration_accesskeyid
  - secretKey: secret-access-key
    remoteRef:
      key: cluster_homelab_garage_migration_secretkey
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secret-manager-store
    kind: ClusterSecretStore
