---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-longhorn-replicated
allowVolumeExpansion: true
parameters:
  fsType: ext4
  staleReplicaTimeout: "2880"
  # as per https://longhorn.io/docs/1.7.1/best-practices/#io-performance
  dataLocality: "best-effort"
  numberOfReplicas: "2"
  recurringJobSelector: '[{"name":"default", "isGroup":true}, {"name":"snapshot-ops", "isGroup":true}]'
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
