---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-longhorn-rwx
allowVolumeExpansion: true
parameters:
  fsType: "ext4"
  nfsOptions: "vers=4.2,noresvport,softerr,timeo=600,retrans=5"
  numberOfReplicas: "3"
  recurringJobSelector: '[{"name":"default", "isGroup":true}, {"name":"snapshot-ops", "isGroup":true}]'
  staleReplicaTimeout: "30"
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
