---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ai/
- dns/
- downloaders/
- home-automation/
- logging/
- loki-query-correctness/
- longhorn-system/
- monitoring/
- object-store-kpi-archive/
- tailscale/
