---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-ai
  namespace: flux-system
spec:
  components:
  - ../../../components/oidc-credentials/openwebui
  - ../../../components/sso
  dependsOn:
  - name: infra-security-extra
    namespace: flux-system
  - name: infra-storage-core
    namespace: flux-system
  - name: infra-networking-core
    namespace: flux-system
  - name: infra-kubernetes-extra
    namespace: flux-system
  interval: 15m0s
  path: ./apps/subsystems/ai
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps-ai
    namespace: flux-system
  timeout: 2m0s
  wait: true
  postBuild:
    substitute:
      secret_store: bitwarden-secret-manager-store
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
  patches:
  # yamllint disable-line rule:indentation
  - patch: |-
      - op: add
        path: /spec/values/extraEnv/-
        value:
          name: OLLAMA_DEBUG
          value: "1"
      - op: add
        path: /spec/values/resources
        value:
          requests:
            memory: 8Gi
            cpu: 4000m
          limits:
            memory: 32Gi
    target:
      kind: HelmRelease
      name: ollama-release
