---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-observability-extra
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-observability-core
    namespace: flux-system
  interval: 15m0s
  path: ./infrastructure/subsystems/observability-extra
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-observability-extra
    namespace: flux-system
  timeout: 2m0s
  wait: true
  postBuild:
    substitute:
      syslogng_loki_url: "loki-write.logging.svc.cluster.local:9095"
      secret_store: bitwarden-secret-manager-store
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
