---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-security-extra
  namespace: flux-system
spec:
  components:
  - ../../../components/db-backups
  dependsOn:
  - name: infra-security-core
    namespace: flux-system
  - name: infra-storage-core
    namespace: flux-system
  - name: infra-database-core
    namespace: flux-system
  interval: 15m0s
  path: ./infrastructure/subsystems/security-extra
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-security-extra
    namespace: flux-system
  timeout: 2m0s
  wait: true
  postBuild:
    substitute:
      cert_issuer: letsencrypt-production-issuer
      db_name: authentik-db
      db_namespace: authentik
      db_replicas: "3"
      db_storage_class: sc-longhorn-local-non-replicated
      db_storage_size: 20Gi
      redis_storage_class: sc-longhorn-replicated
      redis_storage_size: 8Gi
      secret_store: bitwarden-secret-manager-store
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
  patches:
  # yamllint disable-line rule:indentation
  - patch: |-
      - op: add
        path: /spec/backup/barmanObjectStore/serverName
        value: 2025.07.03
      - op: add
        path: /spec/bootstrap/recovery
        value:
          database: authentik
          owner: authentik
          source: origin
      - op: remove
        path: /spec/bootstrap/initdb
      - op: add
        path: /spec/externalClusters
        value:
          - name: origin
            barmanObjectStore:
              data:
                compression: snappy
              destinationPath: s3://nas-cloudnativepg-backups/authentik-db
              endpointURL: https://s3.nas.${domain_name}
              serverName: authentik-db
              s3Credentials:
                accessKeyId:
                  name: authentik-db-backup-credentials
                  key: s3_accesskeyid
                secretAccessKey:
                  name: authentik-db-backup-credentials
                  key: s3_secretaccesskey
              wal:
                compression: snappy
                maxParallel: 8
    target:
      kind: Cluster
      name: authentik-db
      namespace: authentik
