---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-kubernetes-core
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-security-core
    namespace: flux-system
  interval: 15m0s
  path: ./infrastructure/subsystems/kubernetes-core
  postBuild:
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-kubernetes-core
    namespace: flux-system
  timeout: 2m0s
  wait: true
