---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-security-core
  namespace: flux-system
spec:
  components:
  - ../../../components/cert-issuer/letsencrypt
  interval: 15m0s
  path: ./infrastructure/subsystems/security-core
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-security-core
    namespace: flux-system
  timeout: 2m0s
  wait: true
  postBuild:
    substitute:
      secret_store: bitwarden-secret-manager-store
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
