---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-observability-core
  namespace: flux-system
spec:
  components:
  - ../../../components/oidc-credentials/grafana
  - ../../../components/sso
  dependsOn:
  - name: infra-security-core
    namespace: flux-system
  - name: infra-networking-core
    namespace: flux-system
  - name: infra-storage-core
    namespace: flux-system
  interval: 15m0s
  path: ./infrastructure/subsystems/observability-core
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-observability-core
    namespace: flux-system
  timeout: 2m0s
  wait: true
  postBuild:
    substitute:
      # must match the regular expression [0-9]+(ms|s|m|h) (milliseconds seconds minutes hours).
      alertmanager_retention_period: 168h
      alertmanager_storage_class: sc-longhorn-replicated
      alertmanager_storage_size: 2Gi
      # prometheus_retention_period overrides prometheus_retention_size
      # so set:
      #   * prometheus_retention_period = <desired retention period>
      # then tune prometheus_storage_size based on observed pv usage so that
      #   prometheus_retention_size = 70-80% x prometheus_storage_size
      # must match: should match '(^0|([0-9]*[.])?[0-9]+((K|M|G|T|E|P)i?)?B)$'
      prometheus_retention_size: 50GiB
      prometheus_retention_period: 336h
      prometheus_storage_class: sc-longhorn-replicated
      prometheus_storage_size: 60Gi
      prometheus_volume_name: pv-prometheus
      loki_deployment_mode: simple-scalable
      loki_storage_class: sc-longhorn-replicated
      loki_retention_size: 30d
      loki_read_storage_size: 2Gi
      loki_write_storage_size: 16Gi
      loki_backend_storage_size: 2Gi
      loki_singlebinary_storage_size: 2Gi
      loki_results_cache_memory: "1024"
      loki_chunks_cache_memory: "4096"
      # see: https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-substitution-of-numbers-and-booleans
      quote: '"'
      secret_store: bitwarden-secret-manager-store
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
  patches:
  # yamllint disable-line rule:indentation
  - patch: |
      - op: add
        path: /subsets/0/addresses/-
        value: {ip: 192.168.8.64}
      - op: add
        path: /subsets/0/addresses/-
        value: {ip: 192.168.8.65}
      - op: add
        path: /subsets/0/addresses/-
        value: {ip: 192.168.8.67}
      - op: add
        path: /subsets/0/addresses/-
        value: {ip: 192.168.8.68}
      - op: add
        path: /subsets/0/addresses/-
        value: {ip: 192.168.8.69}
    target:
      kind: Endpoints
      name: k3s-metrics-service
  # yamllint disable-line rule:indentation
  - patch: |
      - op: add
        path: /spec/values/prometheus/prometheusSpec/storageSpec/volumeClaimTemplate/metadata/labels
        value:
          recurring-job.longhorn.io/source: enabled
          recurring-job-group.longhorn.io/default: enabled
          recurring-job-group.longhorn.io/snapshot-ops: enabled
          recurring-job-group.longhorn.io/backup-ops: enabled
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: kube-prometheus-stack-release
      namespace: monitoring
