---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-kubernetes-extra
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-kubernetes-core
    namespace: flux-system
  - name: infra-networking-core
    namespace: flux-system
  - name: infra-storage-core
    namespace: flux-system
  interval: 15m0s
  path: ./infrastructure/subsystems/kubernetes-extra
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-kubernetes-extra
    namespace: flux-system
  timeout: 2m0s
  wait: true
  postBuild:
    substitute:
      gpu_shared_across_max_pods: "1"
  patches:
  # yamllint disable-line rule:indentation
  - patch: |-
      - op: add
        path: /spec/values/deschedulerPolicy/profiles/0/pluginConfig/6/args/evictableNamespaces/exclude/-
        value: dns
      - op: add
        path: /spec/values/deschedulerPolicy/profiles/0/pluginConfig/6/args/evictableNamespaces/exclude/-
        value: coder
    target:
      kind: HelmRelease
      name: descheduler-release
      namespace: kube-system
