---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-security-extra
  namespace: flux-system
spec:
  components:
  - ../../../components/db-backups
  - ../../../components/db-restore
  dependsOn:
  - name: infra-security-core
    namespace: flux-system
  - name: infra-storage-core
    namespace: flux-system
  - name: infra-database-core
    namespace: flux-system
  interval: 15m0s
  path: ./infrastructure/subsystems/security-extra
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-security-extra
    namespace: flux-system
  timeout: 2m0s
  wait: true
  postBuild:
    substitute:
      cert_issuer: letsencrypt-production-issuer
      db_name: authentik-db
      db_namespace: authentik
      db_replicas: "3"
      db_restore_database: authentik
      db_restore_owner: authentik
      db_server_name_backup: 2025.07.03
      db_server_name_restore: authentik-db
      db_storage_class: sc-longhorn-local-non-replicated
      db_storage_size: 20Gi
      redis_storage_class: sc-longhorn-replicated
      redis_storage_size: 8Gi
      secret_store: bitwarden-secret-manager-store
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
