---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-networking-extra
  namespace: flux-system
spec:
  components:
  - ../../../components/sso
  dependsOn:
  - name: infra-security-core
    namespace: flux-system
  - name: infra-storage-core
    namespace: flux-system
  - name: infra-networking-core
    namespace: flux-system
  interval: 15m0s
  path: ./infrastructure/subsystems/networking-extra
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-networking-extra
    namespace: flux-system
  timeout: 2m0s
  wait: true
  postBuild:
    substitute:
      secret_store: bitwarden-secret-manager-store
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
  patches:
  # yamllint disable-line rule:indentation
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/6
        value: {name: WEBPASSWORD, value: ""}
    target:
      kind: Deployment
      name: pihole
      namespace: dns
  # yamllint disable-line rule:indentation
  - patch: |-
      $patch: delete
      kind: Deployment
      metadata:
        name: cloudflared-doh
    target:
      kind: Deployment
      name: cloudflared-doh
      namespace: dns
  # yamllint disable-line rule:indentation
  - patch: |-
      $patch: delete
      kind: ExternalSecret
      metadata:
        name: pihole-secrets
    target:
      kind: ExternalSecret
      name: pihole-secrets
      namespace: dns
  # yamllint disable-line rule:indentation
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/linuxserver/unifi-network-application:8.6.9@sha256:f8403a6813b9e0e68fcf622a7f00dbdbd772dfd6a11277fedcb54b816e0eb801
    target:
      kind: Deployment
      name: unifi-network-application
      namespace: unifi
