---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-clusterops-core
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./infrastructure/subsystems/clusterops-core
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-clusterops-core
    namespace: flux-system
  timeout: 2m0s
  wait: true
