---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: policy-pod-security-standards
  namespace: flux-system
spec:
  interval: 1h
  path: ./policies/pod-security-standard/restricted
  prune: true
  sourceRef:
    kind: GitRepository
    name: root
    namespace: flux-system
  timeout: 5m
  wait: false
  patches:
  # yamllint disable-line rule:indentation
  - patch: |-
      - op: replace
        path: /spec/validationFailureAction
        value: Audit
    target:
      kind: ClusterPolicy
