---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: root
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/homelab
  prune: false
  sourceRef:
    kind: GitRepository
    name: root
    namespace: flux-system
