---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  data:
  - secretKey: cert_issuer_email
    remoteRef:
      key: cluster_nas_cert_issuer_email
  - secretKey: dns_zone
    remoteRef:
      key: cluster_nas_dns_zone
  - secretKey: domain_name
    remoteRef:
      key: cluster_nas_domain_name
  - secretKey: externaldns_ip_address
    remoteRef:
      key: cluster_nas_externaldns_ip
  - secretKey: metallb_standard_ip_pool
    remoteRef:
      key: cluster_nas_metallb_ip_pool
  - secretKey: ipaddress_nfs
    remoteRef:
      key: ipaddress_synology_main
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secret-manager-store
    kind: ClusterSecretStore
