---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-data
  namespace: downloaders
  labels:
    app.kubernetes.io/name: bazarr
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sc-longhorn-replicated
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
