---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-data
  namespace: downloaders
  labels:
    app.kubernetes.io/name: overseerr
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sc-longhorn-replicated
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
