---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data
  namespace: downloaders
  labels:
    app.kubernetes.io/name: radarr
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sc-longhorn-replicated
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
