---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-data
  namespace: downloaders
  labels:
    app.kubernetes.io/name: sabnzbd
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sc-longhorn-replicated
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
