"""In-volume manifest writer for the nas object-store trial.

WHY THIS EXISTS
---------------
Longhorn's `backup_*.cfg` carries no digest over the block list it names. Drop
one `Blocks[]` entry and the restore writes a zero-filled hole exactly where
that block belonged -- silently. Longhorn's own block-hash recompute never
fires, because the block was never requested; the restore completes, the volume
attaches, and every status field says healthy.

Nothing store-side can see it either. Referential integrity over the `.cfg`
files verifies that every block a `.cfg` *names* exists; dropping an entry
removes a name, so containment still holds by construction. Offset contiguity
is no help because sparse gaps are legitimate. The only detector available is a
digest taken over the volume's contents *before* the backup and re-checked
after the restore -- which is what this writes.

WHAT IT WRITES, AND WHY EACH PIECE
----------------------------------
1. A deterministic filler file, once.

   A hole landing in unallocated space passes any file-level check, because no
   file's bytes changed. So the manifest's coverage is only ever "whatever the
   application happened to have written" -- neither known nor controlled, and on
   this volume that is a few hundred MiB of small, constantly-rewritten config.
   The filler is a large, stable, never-touched region that a hole cannot fall
   between. Its size is recorded in the manifest so the coverage the check
   actually had is a number an operator can read, not an assumption.

   It is generated from a fixed seed, so it can be regenerated byte-for-byte
   without reference to any backup. That is what makes it *evidence* rather
   than a second copy of something equally suspect.

2. A dated sentinel file, one per run.

   Cheap, and it makes "which days does this restored volume contain" a
   directory listing rather than an inference.

3. `.campaign-manifest.txt` -- sha256, size and mtime of every regular file.

   mtime is recorded for a specific reason. Home Assistant keeps writing during
   the five minutes between this run and the 00:00 backup, so some files
   legitimately differ after a restore. Discriminating those from corruption is
   what mtime buys: a restored file whose mtime is *newer* than the recorded one
   was written after the manifest entry was made, and its digest differing means
   nothing; a restored file whose mtime *matches* the recorded one and whose
   digest does not is corruption, full stop. That is a real discriminator, and
   it is why the permitted-to-differ list can stay as short as it is.

THE PERMITTED-TO-DIFFER LIST TRAVELS INSIDE THE MANIFEST
--------------------------------------------------------
An open-ended exclusion list makes the whole check vacuous, and an exclusion
list supplied at verification time can be widened after the disappointing
result is already on screen. So the list is written into the manifest at
generation time, is exactly the SQLite recorder's WAL/journal sidecars, and the
verifier is expected to read its permitted set from there rather than from an
argument.

FSYNC IS LOAD-BEARING
---------------------
The 00:00 backup snapshots the block device, and this volume runs with
`freezeFilesystemForSnapshot: ignored`. A manifest sitting in page cache is
therefore a manifest that may not be in the backup, or may be in it truncated.
Every file written here is fsynced, and so is each containing directory, before
this exits.

EXIT CODES
----------
0  manifest written.
1  unexpected error.
2  the volume root is missing, or not writable.
3  not enough free space to hold a filler large enough to be worth having.
4  the existing filler's digest does not match the one recorded when it was
   written -- the *live* volume has changed under a file nothing writes to.
   This is not a backup problem and no backup will fix it; stop and read it.
"""

import datetime
import hashlib
import os
import random
import sys

# The volume, as mounted into this pod. Matches Home Assistant's own /config.
VOLUME_ROOT = os.environ.get("VOLUME_ROOT", "/volume")

MANIFEST_NAME = ".campaign-manifest.txt"
SENTINEL_DIR = ".campaign-sentinel"
FILLER_NAME = ".campaign-filler.bin"
FILLER_DIGEST_NAME = ".campaign-filler.sha256"

# Fixed, so the filler is reproducible from this file alone.
FILLER_SEED = 20260908

# Target and floor. The target is a healthy fraction of a 3 GiB volume whose
# application data is under 1 GiB; the floor is the point below which the
# stable-coverage fraction stops being worth the words spent on it. Between the
# two the run shrinks to fit; below the floor it fails rather than quietly
# covering less than it claims.
FILLER_TARGET_BYTES = 1024 * 1024 * 1024
FILLER_MIN_BYTES = 256 * 1024 * 1024

# Headroom left on the filesystem after the filler. Home Assistant filling its
# own config volume is a worse outcome than a smaller filler.
FREE_SPACE_RESERVE_BYTES = 512 * 1024 * 1024

CHUNK = 1024 * 1024

# Exactly the SQLite recorder's sidecars, matched on basename. Recorder runs on
# PostgreSQL here, so on a healthy day this set matches nothing at all -- which
# is the intended state, not a reason to widen it. It is named because a
# recorder that falls back to SQLite writes these two and they are the only
# files on this volume that are legitimately mid-write at any instant.
PERMITTED_TO_DIFFER = (
    "home-assistant_v2.db-wal",
    "home-assistant_v2.db-shm",
    "home-assistant_v2.db-journal",
)


def fsync_path(path):
    fd = os.open(path, os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def write_and_sync(path, data, mode="wb"):
    """Write a file and force it, and its directory entry, to disk."""
    with open(path, mode) as f:
        f.write(data)
        f.flush()
        os.fsync(f.fileno())
    fsync_path(os.path.dirname(path))


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            block = f.read(CHUNK)
            if not block:
                break
            h.update(block)
    return h.hexdigest()


def choose_filler_size(root, already_have):
    """Largest filler that leaves the reserve intact, or None if too small.

    `already_have` is the size of a filler that exists on disk: its blocks are
    already spent, so they count as available when deciding whether a target of
    the same size still fits.
    """
    st = os.statvfs(root)
    spendable = st.f_bavail * st.f_frsize + already_have - FREE_SPACE_RESERVE_BYTES
    if spendable >= FILLER_TARGET_BYTES:
        return FILLER_TARGET_BYTES
    if spendable >= FILLER_MIN_BYTES:
        # Round down to whole MiB so the size is a readable number in the
        # manifest header and identical across runs at the same free space.
        return (int(spendable) // CHUNK) * CHUNK
    return None


def generate_filler(path, size):
    """Write `size` bytes of seeded pseudorandom data.

    Pseudorandom rather than a repeating pattern: the backup is lz4-compressed,
    and a compressible filler would occupy the volume blocks this check needs
    covered while costing almost nothing in the backup -- which sounds like a
    free win and is in fact the shape that makes a measurement unrepresentative
    of the thing being measured. The cost is a first full backup roughly a GiB
    larger; every later incremental is unaffected, because this file is written
    once and never touched again.
    """
    rnd = random.Random(FILLER_SEED)
    written = 0
    with open(path, "wb") as f:
        while written < size:
            n = min(CHUNK, size - written)
            f.write(rnd.randbytes(n))
            written += n
        f.flush()
        os.fsync(f.fileno())
    fsync_path(os.path.dirname(path))


def ensure_filler(root):
    """Create the filler if absent; verify it if present. Returns (path, size, digest)."""
    path = os.path.join(root, FILLER_NAME)
    digest_path = os.path.join(root, FILLER_DIGEST_NAME)

    if os.path.exists(path) and os.path.exists(digest_path):
        with open(digest_path) as f:
            expected = f.read().split()[0]
        actual = sha256_file(path)
        size = os.path.getsize(path)
        if actual != expected:
            print(
                f"FATAL: filler digest mismatch on the LIVE volume: expected {expected}, "
                f"read {actual}. Nothing writes to this file. This is not something a "
                f"restore will fix and it invalidates today's manifest.",
                file=sys.stderr,
            )
            sys.exit(4)
        print(f"filler: verified {size} bytes, sha256 {actual}")
        return path, size, actual

    already_have = os.path.getsize(path) if os.path.exists(path) else 0
    size = choose_filler_size(root, already_have)
    if size is None:
        st = os.statvfs(root)
        print(
            f"FATAL: only {st.f_bavail * st.f_frsize} bytes free; a filler of at least "
            f"{FILLER_MIN_BYTES} bytes cannot be written while leaving "
            f"{FREE_SPACE_RESERVE_BYTES} bytes of headroom. Refusing to write a manifest "
            f"whose coverage would be smaller than it claims.",
            file=sys.stderr,
        )
        sys.exit(3)

    if size != FILLER_TARGET_BYTES:
        print(f"WARNING: filler shrunk to {size} bytes to keep {FREE_SPACE_RESERVE_BYTES} bytes free")

    print(f"filler: generating {size} bytes from seed {FILLER_SEED}")
    generate_filler(path, size)
    digest = sha256_file(path)
    write_and_sync(digest_path, f"{digest}  {FILLER_NAME}\n".encode())
    print(f"filler: wrote {size} bytes, sha256 {digest}")
    return path, size, digest


def write_sentinel(root, now):
    directory = os.path.join(root, SENTINEL_DIR)
    os.makedirs(directory, exist_ok=True)
    fsync_path(root)
    path = os.path.join(directory, f"{now:%Y-%m-%d}.txt")
    body = (
        f"nas object-store trial sentinel\n"
        f"written_at {now:%Y-%m-%dT%H:%M:%SZ}\n"
        f"node {os.environ.get('NODE_NAME', 'unknown')}\n"
        f"pod {os.environ.get('POD_NAME', 'unknown')}\n"
    )
    write_and_sync(path, body.encode())
    return path


def walk(root):
    """Every regular file under root, relative-pathed and sorted.

    Returns (entries, skipped) where skipped names anything that is not a
    regular file. Skipped entries are reported rather than dropped: a manifest
    that silently omits things is the failure mode this whole exercise exists to
    avoid.
    """
    entries = []
    skipped = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for name in sorted(filenames):
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, root)
            if rel == MANIFEST_NAME:
                # Structurally excluded: a file cannot contain its own digest.
                continue
            try:
                st = os.lstat(full)
            except OSError as exc:
                skipped.append((rel, f"lstat failed: {exc}"))
                continue
            if not os.path.isfile(full) or os.path.islink(full):
                skipped.append((rel, "not a regular file"))
                continue
            try:
                entries.append((rel, sha256_file(full), st.st_size, st.st_mtime_ns))
            except OSError as exc:
                skipped.append((rel, f"read failed: {exc}"))
    entries.sort()
    return entries, skipped


def main():
    now = datetime.datetime.now(datetime.timezone.utc)
    root = VOLUME_ROOT

    if not os.path.isdir(root):
        print(f"FATAL: {root} is not a directory", file=sys.stderr)
        return 2
    if not os.access(root, os.W_OK):
        print(f"FATAL: {root} is not writable", file=sys.stderr)
        return 2

    filler_path, filler_size, filler_digest = ensure_filler(root)
    sentinel_path = write_sentinel(root, now)
    print(f"sentinel: {sentinel_path}")

    entries, skipped = walk(root)
    total_bytes = sum(e[2] for e in entries)

    lines = [
        "# campaign-manifest v1",
        f"# generated_at {now:%Y-%m-%dT%H:%M:%SZ}",
        f"# generated_at_epoch {now.timestamp():.6f}",
        f"# volume_root {root}",
        f"# filler_path {os.path.relpath(filler_path, root)}",
        f"# filler_seed {FILLER_SEED}",
        f"# filler_size {filler_size}",
        f"# filler_sha256 {filler_digest}",
        f"# files {len(entries)}",
        f"# bytes {total_bytes}",
        f"# skipped {len(skipped)}",
    ]
    lines += [f"# permitted_to_differ {name}" for name in PERMITTED_TO_DIFFER]
    lines += [f"# skipped_entry {rel}\t{why}" for rel, why in skipped]
    lines += ["# columns sha256\tsize\tmtime_ns\tpath"]
    lines += [f"{digest}\t{size}\t{mtime}\t{rel}" for rel, digest, size, mtime in entries]

    manifest_path = os.path.join(root, MANIFEST_NAME)
    write_and_sync(manifest_path, ("\n".join(lines) + "\n").encode())

    print(
        f"manifest: {len(entries)} files, {total_bytes} bytes covered "
        f"({filler_size} of it stable filler), {len(skipped)} skipped"
    )
    if skipped:
        for rel, why in skipped:
            print(f"  skipped {rel}: {why}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except SystemExit:
        raise
    except Exception as exc:  # noqa: BLE001 - the exit code is the contract
        print(f"FATAL: {exc}", file=sys.stderr)
        sys.exit(1)
