---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  data:
  - secretKey: cert_issuer_email
    remoteRef:
      key: cluster_homelab_cert_issuer_email
  - secretKey: dns_zone
    remoteRef:
      key: cluster_homelab_dns_zone
  - secretKey: domain_name
    remoteRef:
      key: cluster_homelab_domain_name
  - secretKey: externaldns_ip_address
    remoteRef:
      key: cluster_homelab_externaldns_ip
  - secretKey: metallb_standard_ip_pool
    remoteRef:
      key: cluster_homelab_metallb_ip_pool
  - secretKey: pihole_external_ip_address
    remoteRef:
      key: cluster_homelab_pihole_ip
  - secretKey: unifi_external_ip_address
    remoteRef:
      key: cluster_homelab_unifi_ip
  - secretKey: plex_external_ip_address
    remoteRef:
      key: cluster_homelab_plex_ip
  - secretKey: syslog_external_ip_address
    remoteRef:
      key: cluster_homelab_syslog_ip
  - secretKey: jellyfin_external_ip_address
    remoteRef:
      key: cluster_homelab_jellyfin_ip
  - secretKey: ipaddress_nfs
    remoteRef:
      key: ipaddress_synology_main
  - secretKey: freeradius_external_ip_address
    remoteRef:
      key: cluster_homelab_freeradius_ip
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secret-manager-store
    kind: ClusterSecretStore
