---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyoming-whisper-data
  namespace: home-automation
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sc-longhorn-replicated
  resources:
    requests:
      storage: 3Gi
