---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  namespace: obsidian-vault
  labels:
    app.kubernetes.io/name: obsidian-vault
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-longhorn-rwx
  volumeMode: Filesystem
