---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coder-workspace-home
  namespace: coder
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      # must match the value specified within the static-nfs-share-media-rwx volume
      storage: 1Gi
  storageClassName: sc-nfs-share
  volumeName: static-nfs-share-coder-rwx
