{
 "title": "Spegel",
 "description": "Spegel is a pull only OCI registry which runs locally on every Node in the Kubernetes cluster. Containerd is configured to use the local registry as a mirror, which would serve the image from within the cluster or from the source registry.",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "container", "label": "container", "query": "registry" },
   {
    "name": "registry",
    "label": "registry",
    "query": {
     "query": "label_values(spegel_advertised_keys,registry) "
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Registry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(spegel_advertised_keys{registry=~\"$registry\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_node_name{job=\"kubelet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kubelet_running_pods)", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "spegel_advertised_images{registry=~\"$registry\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spegel_advertised_keys{registry=~\"$registry\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "datasource" },
  {
   "title": "Container Images Advertised ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "spegel_advertised_images{registry=~\"$registry\"}",
     "legendFormat": "{{ registry }}"
    }
   ]
  },
  {
   "title": "Images Layer Advertised ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "spegel_advertised_keys{registry=~\"$registry\"} ",
     "legendFormat": "{{ registry }}"
    }
   ]
  },
  { "title": "Kubelet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Kubelet Operation Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_total{job=\"kubelet\", metrics_path=\"/metrics\", operation_type=~\"list_images|pull_image|start_container|list_images|list_containers|version|exec_sync|create_container\"}[$__rate_interval])) by (operation_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubelet Operation Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors_total{job=\"kubelet\", metrics_path=\"/metrics\",operation_type=~\"list_images|pull_image|start_container|list_images|list_containers|version|exec_sync|create_container\"}[$__rate_interval])) by (operation_type)",
     "legendFormat": "{{instance}} {{operation_type}}"
    }
   ]
  }
 ]
}