---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: minio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      # must match the value specified in PV
      storage: 1Gi
  storageClassName: sc-nfs-share
  volumeName: static-nfs-share-nas-minio
