---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: grafana-extra-config
  namespace: monitoring
  files:
  - conf.d/grafana-dashboards.yaml
  options:
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled
    disableNameSuffixHash: true
- name: dashboard-spegel
  namespace: monitoring
  files:
  - dashboards/spegel.json
  options:
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled
    labels:
      grafana_dashboard: "1"
    disableNameSuffixHash: true
- name: dashboard-prometheus-tuning
  namespace: monitoring
  files:
  - dashboards/prometheus-tuning.json
  options:
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled
    labels:
      grafana_dashboard: "1"
    disableNameSuffixHash: true
- name: snmp-exporter-extra-config
  namespace: monitoring
  files:
  - conf.d/scrape-configs.yaml
  options:
    disableNameSuffixHash: true
