---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- freetube-data.yaml
- jellyfin-data.yaml
- media-read-only.yaml
- plex-data.yaml
- tautulli-data.yaml

patches:
# yamllint disable-line rule:indentation
- patch: |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: irrelevant
      labels:
        recurring-job.longhorn.io/source: enabled
        recurring-job-group.longhorn.io/default: enabled
        recurring-job-group.longhorn.io/snapshot-ops: enabled
        recurring-job-group.longhorn.io/backup-ops: enabled
  target:
    kind: PersistentVolumeClaim
    name: '^.+-data$'
