---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-read-only
  namespace: media
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      # must match the value specified within the static-nfs-share-media-rwx volume
      storage: 1Gi
  storageClassName: sc-nfs-share
  volumeName: static-nfs-share-media-rox
