---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-nfs-share-harbor-database
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: ${ipaddress_nfs}#volume1#kubernetes-harbor-database
    volumeAttributes:
      server: ${ipaddress_nfs}
      share: /volume1/kubernetes-harbor/database
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-nfs-share
