---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../baseline
- disallow-capabilities-strict.yaml
- disallow-privilege-escalation.yaml
- require-run-as-non-root-user.yaml
- require-run-as-nonroot.yaml
- restrict-seccomp-strict.yaml
- restrict-volume-types.yaml
