---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-storage
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-storage-csi-driver-nfs
    namespace: flux-system
  interval: 15m0s
  path: ./clusters/nas/storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: root-secondary
    namespace: flux-system
  timeout: 2m0s
  wait: true
  postBuild:
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
