---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-clusterops-core
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./infrastructure/subsystems/clusterops-core
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-clusterops-core
    namespace: flux-system
  timeout: 2m0s
  wait: true
  patches:
  # yamllint disable-line rule:indentation
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits/cpu
    target:
      kind: Deployment
      namespace: flux-system
