---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-storage-csi-driver-nfs
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./infrastructure/subsystems/storage-core/csi-driver-nfs
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-storage-core
    namespace: flux-system
  timeout: 2m0s
  wait: true
  postBuild:
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
