---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-storage-minio
  namespace: flux-system
spec:
  components:
  - ../../../../components/oidc-credentials/minio
  - ../../../../components/sso
  dependsOn:
  - name: infra-storage-csi-driver-nfs
    namespace: flux-system
  - name: config-storage
    namespace: flux-system
  interval: 15m0s
  path: ./infrastructure/subsystems/storage-core/minio
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-storage-core
    namespace: flux-system
  timeout: 2m0s
  wait: true
  postBuild:
    substitute:
      oidc_minio_app_name: minio-nas
      oidc_minio_clientid_key: oidc_minionas_clientid
      oidc_minio_clientsecret_key: oidc_minionas_clientsecret
      secret_store: bitwarden-secret-manager-store
      minio_admin_username_key: cluster_nas_minio_admin_username
      minio_admin_password_key: cluster_nas_minio_admin_password
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
  patches:
  # yamllint disable-line rule:indentation
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: minio-release
        namespace: minio
      spec:
        values:
          ingress:
            enabled: true
          persistence:
            enabled: true
            existingClaim: minio-data
          securityContext:
            fsGroup: 65539
            fsGroupChangePolicy: "OnRootMismatch"
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: minio-release
      namespace: minio
