---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- helm-repository-authentik.yaml
- helm-release-authentik-outpost.yaml
- middleware-forward-auth.yaml
- ingress-authentik-outpost.yaml

commonAnnotations:
  # as this is a critical infrastructure component, prevent pruning unintentionally
  kustomize.toolkit.fluxcd.io/prune: disabled
