---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik-outpost-release
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik-remote-cluster
      interval: 24h0m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authentik-repository
        namespace: flux-system
      version: 2.1.0
  install:
    createNamespace: false
    remediation:
      retries: 3
  interval: 15m0s
  releaseName: authentik-outpost
  targetNamespace: authentik
  upgrade:
    cleanupOnFail: true
    remediation:
      ignoreTestFailures: false
      retries: 3
      strategy: rollback
  values: {}
