---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps-bitwarden
  namespace: flux-system
spec:
  ignore: |
    # exclude all
    /*
    # include the corresponding apps subsystems directory
    !/apps/subsystems/bitwarden
  interval: 1m0s
  ref:
    tag: apps-bitwarden-v0.0.21
  url: https://github.com/ppat/homelab-ops-kubernetes-apps.git
