---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- root.yaml
- infra-helm-repositories.yaml
- infra-clusterops-core.yaml
- infra-kubernetes-core.yaml
- infra-networking-core.yaml
- infra-security-core.yaml
- infra-storage-core.yaml
- apps-helm-repositories.yaml
- apps-bitwarden.yaml
- apps-harbor.yaml

sortOptions:
  order: fifo
