---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui
  namespace: ai
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: sc-longhorn-replicated
  volumeMode: Filesystem
