---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data
  namespace: media
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sc-longhorn-replicated
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
