---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra-observability-extra
  namespace: flux-system
spec:
  ignore: |
    # exclude all
    /*
    # include the corresponding infrastructure subsystems directory
    !/infrastructure/subsystems/observability-extra
  interval: 1m0s
  ref:
    tag: infra-observability-extra-v0.1.12
  url: https://github.com/ppat/homelab-ops-kubernetes-apps.git
