---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra-storage-core
  namespace: flux-system
spec:
  ignore: |
    # exclude all
    /*
    # include components
    !/components
    # include the corresponding infrastructure subsystems directory
    !/infrastructure/subsystems/storage-core
  interval: 1m0s
  ref:
    tag: infra-storage-core-v0.1.0
  url: https://github.com/ppat/homelab-ops-kubernetes-apps.git
