---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra-helm-repositories
  namespace: flux-system
spec:
  ignore: |
    # exclude all
    /*
    # include the corresponding infrastructure helm repositories
    !/infrastructure/helm-repositories
  interval: 1m0s
  ref:
    tag: infra-helm-repositories-v0.1.1
  url: https://github.com/ppat/homelab-ops-kubernetes-apps.git
