---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra-kubernetes-extra
  namespace: flux-system
spec:
  ignore: |
    # exclude all
    /*
    # include the corresponding infrastructure subsystems directory
    !/infrastructure/subsystems/kubernetes-extra
  interval: 1m0s
  ref:
    tag: infra-kubernetes-extra-v0.0.17
  url: https://github.com/ppat/homelab-ops-kubernetes-apps.git
