---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra-networking-extra
  namespace: flux-system
spec:
  ignore: |
    # exclude all
    /*
    # include components
    !/components
    # include the corresponding infrastructure subsystems directory
    !/infrastructure/subsystems/networking-extra
  interval: 1m0s
  ref:
    tag: infra-networking-extra-v0.3.2
  url: https://github.com/ppat/homelab-ops-kubernetes-apps.git
