---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra-clusterops-core
  namespace: flux-system
spec:
  ignore: |
    # exclude all
    /*
    # include the corresponding infrastructure subsystems directory
    !/infrastructure/subsystems/clusterops-core
  interval: 1m0s
  ref:
    tag: infra-clusterops-core-v0.0.16
  url: https://github.com/ppat/homelab-ops-kubernetes-apps.git
