---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- root.yaml
- infra-clusterops-core.yaml
- infra-database-core.yaml
- infra-kubernetes-core.yaml
- infra-kubernetes-extra.yaml
- infra-networking-core.yaml
- infra-networking-extra.yaml
- infra-observability-core.yaml
- infra-observability-extra.yaml
- infra-security-core.yaml
- infra-security-extra.yaml
- infra-storage-core.yaml
- apps-ai.yaml
- apps-coder.yaml
- apps-downloaders.yaml
- apps-home-automation.yaml
- apps-media.yaml
- apps-misc.yaml
