---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: litellm-model-config
  namespace: ai
  files:
  - conf.d/model-config.yaml
  options:
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled
    disableNameSuffixHash: true
