---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- disallow-capabilities.yaml
- disallow-host-namespaces.yaml
- disallow-host-path.yaml
- disallow-host-ports.yaml
- disallow-host-process.yaml
- disallow-privileged-containers.yaml
- disallow-proc-mount.yaml
- disallow-selinux.yaml
- restrict-apparmor-profiles.yaml
- restrict-seccomp.yaml
- restrict-sysctls.yaml
