---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- daily-backup.yaml
- weekday-snapshot.yaml
- weekend-snapshot.yaml
# - weekly-filesystem-trim.yaml
- weekly-snapshot-cleanup.yaml
- weekly-system-snapshot-cleanup.yaml
