---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: weekend-snapshot
  namespace: longhorn-system
spec:
  task: snapshot
  concurrency: 3
  cron: "0 12,20 * * 6,0"  # twice a day during the day on weekends (avoiding system maintenance/downtime time windows)
  groups:
  - snapshot-ops
  retain: 8
