---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: minio
  labels:
    app.kubernetes.io/name: minio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: sc-longhorn-replicated
  volumeMode: Filesystem
