---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-logs
  namespace: dns
  labels:
    app.kubernetes.io/name: pihole
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: sc-longhorn-replicated
  volumeMode: Filesystem
