---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-logs
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: sc-longhorn-replicated
  volumeMode: Filesystem
