---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-logs
  namespace: unifi
  labels:
    app.kubernetes.io/name: unifi-network-application
    app.kubernetes.io/part-of: unifi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: sc-longhorn-replicated
  volumeMode: Filesystem
